#edit aws things before deployment
spring.application.name=Prod-spring-fvu-app

server.port=8081

#Uncomment for aws setup
# FVU JAR path (Linux EC2 path)




#fvu.jar.path=/home/ubuntu/TDS_STANDALONE_FVU_9.2/TDS_STANDALONE_FVU_9.2.jar
#
## Output folder for temporary processing
#fvu.output.dir=/home/ubuntu/fvu-output

#For Local trial of this prod ready fvu with aws n s3
#fvu.jar.path=C:\\Users\\vshrama\\TDS_STANDALONE_FVU_9.2\\TDS_STANDALONE_FVU_9.2.jar
#fvu.output.dir=C:\\Users\\vshrama\\Desktop\\Output

#Dockerize paths
fvu.output.dir=/app/output
fvu.jar.path=/app/FVU/TDS_RPU_5.8/TDS_STANDALONE_FVU_9.3.jar
#
#May want to reduced depending on need
fvu.max.concurrent=5
  
# Storage Provider
storage.provider=${STORAGE_PROVIDER:s3}

#AWS CREDENTIALS
aws.region=${AWS_REGION:dummy}
s3.bucket.name=${S3_BUCKET_NAME:dummy}
aws.accessKeyId=${AWS_ACCESS_KEY_ID:dummy}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:dummy}


#MINIO Credentials
minio.endpoint=${MINIO_ENDPOINT:}
minio.accessKey=${MINIO_ACCESS_KEY:}
minio.secretKey=${MINIO_SECRET_KEY:}
minio.bucket=${MINIO_BUCKET:}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:3300}
spring.data.redis.timeout=10000ms
spring.data.redis.lettuce.pool.max-active=5
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=2
spring.jackson.serialization.indent-output=true
job.status.ttl.hours=24

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


